FROM postgres:18-alpine

LABEL maintainer="Dolorestec Team" \
      version="v18" \
      description="PostgreSQL custom image for Dolorestec"

# Expor porta
EXPOSE 5432

# Comando padrão
CMD ["postgres"]