FROM sonatype/nexus3:latest

LABEL maintainer="Dolorestec Team" \
      version="v0.1.0" \
      description="Nexus Repository custom image for Dolorestec"

# Expor porta
EXPOSE 8081

# Comando padrão
CMD ["/opt/sonatype/nexus/bin/nexus", "run"]