name: 'Build Docker Images'
description: 'Build all Docker images for validation'
inputs:
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: false
    default: 'docker'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build PostgreSQL
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/postgres/Dockerfile
        tags: dolorestec/postgres:validate
        push: false

    - name: Build Redis
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/redis/Dockerfile
        tags: dolorestec/redis:validate
        push: false

    - name: Build RabbitMQ
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/rabbitmq/Dockerfile
        tags: dolorestec/rabbitmq:validate
        push: false

    - name: Build GitHub Runner
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/github-runner/Dockerfile
        tags: dolorestec/github-runner:validate
        push: false

    - name: Build Traefik
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/traefik/Dockerfile
        tags: dolorestec/traefik:validate
        push: false

    - name: Build Nexus
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/nexus/Dockerfile
        tags: dolorestec/nexus:validate
        push: false