name: 'Lint Files'
description: 'Run linting on all project files'
inputs:
  files:
    description: 'Files to lint'
    required: false
    default: '.'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Super Linter
      uses: super-linter/super-linter@v6.8.0
      env:
        DEFAULT_BRANCH: develop
        GITHUB_TOKEN: ${{ github.token }}
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_DOCKERFILE: true
        VALIDATE_YAML: true
        VALIDATE_JSON: true
        VALIDATE_BASH: true
        VALIDATE_SHELL_SHFMT: true