name: "Build and Push Docker Image"
description: "A local composite action that builds Docker images with buildx and pushes to a registry. Avoids external setup actions by running commands directly."
inputs:
  image:
    description: 'Image name (including registry and repository), e.g. ghcr.io/owner/image'
    required: true
  tags:
    description: 'Comma-separated list of tags to apply (e.g. latest,sha)'
    required: true
  context:
    description: 'Build context directory'
    required: true
    default: '.'
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
    default: 'Dockerfile'
  entrypoint:
    description: 'Path to entrypoint in context (not used by buildx, kept for compatibility)'
    required: false
    default: 'entrypoint.sh'
  push:
    description: 'Whether to push the built image (true/false)'
    required: false
    default: 'true'
  registry:
    description: 'Registry host (e.g. ghcr.io)'
    required: false
    default: 'ghcr.io'
  registry_username:
    description: 'Registry username'
    required: false
    default: ''
  registry_password:
    description: 'Registry password (or token)'
    required: false
    default: ''
  platforms:
    description: 'Comma-separated platforms for buildx (e.g. linux/amd64,linux/arm64)'
    required: false
    default: 'linux/amd64'

runs:
  using: 'composite'
  steps:
    - name: Setup QEMU (register binfmt handlers)
      shell: bash
      run: |
        # register qemu handlers so buildx can build multi-arch images
        docker run --rm --privileged tonistiigi/binfmt --install all || true

    - name: Create or use buildx builder
      shell: bash
      run: |
        set -e
        docker buildx inspect buildx_builder >/dev/null 2>&1 || docker buildx create --name buildx_builder --use
        docker buildx use buildx_builder

    - name: Login to registry (if credentials provided)
      if: ${{ inputs.registry_password != '' }}
      shell: bash
      run: |
        echo "Logging in to registry ${{ inputs.registry }}"
        echo "${{ inputs.registry_password }}" | docker login ${{ inputs.registry }} -u "${{ inputs.registry_username }}" --password-stdin

    - name: Build and push (buildx)
      shell: bash
      run: |
        set -euo pipefail
        IMAGE="${{ inputs.image }}"
        TAGS="${{ inputs.tags }}"
        DOCKERFILE="${{ inputs.dockerfile }}"
        CTX="${{ inputs.context }}"
        PLATFORMS="${{ inputs.platforms }}"
        PUSH="${{ inputs.push }}"

        # Build tag arguments
        TAG_ARGS=()
        for t in $(echo "$TAGS" | tr ',' ' '); do
          TAG_ARGS+=( -t "${IMAGE}:$t" )
        done

        echo "Building ${IMAGE} tags: $TAGS platforms: $PLATFORMS"

        if [ "$PUSH" = "true" ]; then
          docker buildx build --builder buildx_builder --platform "$PLATFORMS" -f "$DOCKERFILE" "${TAG_ARGS[@]}" "$CTX" --push
        else
          docker buildx build --builder buildx_builder --platform "$PLATFORMS" -f "$DOCKERFILE" "${TAG_ARGS[@]}" "$CTX" --load
        fi