name: 'Docker Build Action'
description: 'Reusable action for building and pushing Docker images'
inputs:
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  context:
    description: 'Build context'
    required: false
    default: '.'
  image-name:
    description: 'Base image name'
    required: true
  version:
    description: 'Version tag'
    required: true
  registry:
    description: 'Registry URL'
    required: true
  username:
    description: 'Registry username'
    required: true
  password:
    description: 'Registry password'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Login to registry
      run: |
        echo "Logging into ${{ inputs.registry }}"
        echo "${{ inputs.password }}" | docker login ${{ inputs.registry }} -u ${{ inputs.username }} --password-stdin
      shell: bash
    - name: Build Docker image
      run: |
        echo "Building Docker image: ${{ inputs.image-name }}:${{ inputs.version }}"
        docker build -f ${{ inputs.dockerfile }} -t ${{ inputs.image-name }}:${{ inputs.version }} ${{ inputs.context }}
      shell: bash
    - name: Tag and push
      run: |
        FULL_IMAGE=${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.version }}
        docker tag ${{ inputs.image-name }}:${{ inputs.version }} $FULL_IMAGE
        docker push $FULL_IMAGE
        echo "Pushed to $FULL_IMAGE"
      shell: bash